name: sample
on: [push]
env:
  SAMPLE: "This is a test run"
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: firststep
        id: first-step
        run: |
          echo "-------------gawdfhvahfa-------------------"
          echo "------fisrt job----------------"
          name_act=" GITHUB ACTIONS"
          
  second-job:
    needs: [first-job]
    name: Second JOB
    runs-on: ubuntu-latest
    steps:
      - name: output from previous job
        run: |
          echo "This is the output"
          
  third-job:
    needs: [second-job]
    name: THird Job
    runs-on: ubuntu-latest
    steps:
      - name: no dependency
        run: |
          echo "HEY this is a test"
